SET FOREIGN_KEY_CHECKS=0;
SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

CREATE DATABASE IF NOT EXISTS `mimiciiiv14` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci;
USE `mimiciiiv14`;

CREATE TABLE `ADMISSIONS` (
  `ROW_ID` mediumint UNSIGNED NOT NULL,
  `SUBJECT_ID` mediumint UNSIGNED NOT NULL,
  `HADM_ID` mediumint UNSIGNED NOT NULL,
  `ADMITTIME` datetime NOT NULL,
  `DISCHTIME` datetime NOT NULL,
  `LENGTH_OF_STAY` int NOT NULL,
  `DEATHTIME` datetime DEFAULT NULL,
  `ADMISSION_TYPE` varchar(50) NOT NULL,
  `ADMISSION_LOCATION` varchar(50) NOT NULL,
  `DISCHARGE_LOCATION` varchar(50) NOT NULL,
  `EDREGTIME` datetime DEFAULT NULL,
  `EDOUTTIME` datetime DEFAULT NULL,
  `DIAGNOSIS` varchar(255) DEFAULT NULL,
  `HOSPITAL_EXPIRE_FLAG` tinyint UNSIGNED NOT NULL,
  `HAS_CHARTEVENTS_DATA` tinyint UNSIGNED NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `CALLOUT` (
  `ROW_ID` mediumint UNSIGNED NOT NULL,
  `SUBJECT_ID` mediumint UNSIGNED NOT NULL,
  `HADM_ID` mediumint UNSIGNED NOT NULL,
  `SUBMIT_WARDID` tinyint UNSIGNED DEFAULT NULL,
  `SUBMIT_CAREUNIT` varchar(15) DEFAULT NULL,
  `CURR_WARDID` tinyint UNSIGNED DEFAULT NULL,
  `CURR_CAREUNIT` varchar(15) DEFAULT NULL,
  `CALLOUT_WARDID` tinyint UNSIGNED NOT NULL,
  `CALLOUT_SERVICE` varchar(10) NOT NULL,
  `REQUEST_TELE` tinyint UNSIGNED NOT NULL,
  `REQUEST_RESP` tinyint UNSIGNED NOT NULL,
  `REQUEST_CDIFF` tinyint UNSIGNED NOT NULL,
  `REQUEST_MRSA` tinyint UNSIGNED NOT NULL,
  `REQUEST_VRE` tinyint UNSIGNED NOT NULL,
  `CALLOUT_STATUS` varchar(20) NOT NULL,
  `CALLOUT_OUTCOME` varchar(20) NOT NULL,
  `DISCHARGE_WARDID` tinyint UNSIGNED DEFAULT NULL,
  `ACKNOWLEDGE_STATUS` varchar(20) NOT NULL,
  `CREATETIME` datetime NOT NULL,
  `UPDATETIME` datetime NOT NULL,
  `ACKNOWLEDGETIME` datetime DEFAULT NULL,
  `OUTCOMETIME` datetime NOT NULL,
  `FIRSTRESERVATIONTIME` datetime DEFAULT NULL,
  `CURRENTRESERVATIONTIME` datetime DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `CAREGIVERS` (
  `ROW_ID` mediumint UNSIGNED NOT NULL,
  `CGID` smallint UNSIGNED NOT NULL,
  `first_name` varchar(128) NOT NULL,
  `last_name` varchar(128) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `NPI_number` varchar(11) NOT NULL,
  `gender` varchar(16) NOT NULL,
  `LABEL` varchar(15) DEFAULT NULL,
  `DESCRIPTION` varchar(30) DEFAULT NULL,
  `fhir_json` varchar(2000) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `chartevents` (
  `ROW_ID` int UNSIGNED NOT NULL,
  `SUBJECT_ID` mediumint UNSIGNED NOT NULL,
  `HADM_ID` mediumint UNSIGNED DEFAULT NULL,
  `ICUSTAY_ID` mediumint UNSIGNED DEFAULT NULL,
  `ITEMID` mediumint UNSIGNED NOT NULL,
  `CHARTTIME` datetime NOT NULL,
  `STORETIME` datetime DEFAULT NULL,
  `CGID` smallint UNSIGNED DEFAULT NULL,
  `VALUE` text,
  `VALUENUM` decimal(22,10) DEFAULT NULL,
  `VALUEUOM` varchar(50) DEFAULT NULL,
  `WARNING` tinyint UNSIGNED DEFAULT NULL,
  `ERROR` tinyint UNSIGNED DEFAULT NULL,
  `RESULTSTATUS` varchar(50) DEFAULT NULL,
  `STOPPED` varchar(50) DEFAULT NULL,
  `acd_study` tinyint(1) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `CPTEVENTS` (
  `ROW_ID` mediumint UNSIGNED NOT NULL,
  `SUBJECT_ID` mediumint UNSIGNED NOT NULL,
  `HADM_ID` mediumint UNSIGNED NOT NULL,
  `COSTCENTER` varchar(10) NOT NULL,
  `CHARTDATE` datetime DEFAULT NULL,
  `CPT_CD` varchar(10) NOT NULL,
  `CPT_NUMBER` mediumint UNSIGNED DEFAULT NULL,
  `CPT_SUFFIX` varchar(5) DEFAULT NULL,
  `TICKET_ID_SEQ` smallint UNSIGNED DEFAULT NULL,
  `SECTIONHEADER` varchar(50) DEFAULT NULL,
  `SUBSECTIONHEADER` varchar(255) DEFAULT NULL,
  `DESCRIPTION` varchar(200) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `DATETIMEEVENTS` (
  `ROW_ID` mediumint UNSIGNED NOT NULL,
  `SUBJECT_ID` mediumint UNSIGNED NOT NULL,
  `HADM_ID` mediumint UNSIGNED DEFAULT NULL,
  `ICUSTAY_ID` mediumint UNSIGNED DEFAULT NULL,
  `ITEMID` mediumint UNSIGNED NOT NULL,
  `CHARTTIME` datetime NOT NULL,
  `STORETIME` datetime NOT NULL,
  `CGID` smallint UNSIGNED NOT NULL,
  `VALUE` datetime DEFAULT NULL,
  `VALUEUOM` varchar(50) NOT NULL,
  `WARNING` tinyint UNSIGNED DEFAULT NULL,
  `ERROR` tinyint UNSIGNED DEFAULT NULL,
  `RESULTSTATUS` varchar(50) DEFAULT NULL,
  `STOPPED` varchar(50) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `DIAGNOSES_ICD` (
  `ROW_ID` mediumint UNSIGNED NOT NULL,
  `SUBJECT_ID` mediumint UNSIGNED NOT NULL,
  `HADM_ID` mediumint UNSIGNED NOT NULL,
  `SEQ_NUM` tinyint UNSIGNED DEFAULT NULL,
  `ICD9_CODE` varchar(10) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `DRGCODES` (
  `ROW_ID` mediumint UNSIGNED NOT NULL,
  `SUBJECT_ID` mediumint UNSIGNED NOT NULL,
  `HADM_ID` mediumint UNSIGNED NOT NULL,
  `DRG_TYPE` varchar(20) NOT NULL,
  `DRG_CODE` varchar(20) NOT NULL,
  `DESCRIPTION` varchar(255) DEFAULT NULL,
  `DRG_SEVERITY` tinyint UNSIGNED DEFAULT NULL,
  `DRG_MORTALITY` tinyint UNSIGNED DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `D_CPT` (
  `ROW_ID` tinyint UNSIGNED NOT NULL,
  `CATEGORY` tinyint UNSIGNED NOT NULL,
  `SECTIONRANGE` varchar(100) NOT NULL,
  `SECTIONHEADER` varchar(50) NOT NULL,
  `SUBSECTIONRANGE` varchar(100) NOT NULL,
  `SUBSECTIONHEADER` varchar(255) NOT NULL,
  `CODESUFFIX` varchar(5) DEFAULT NULL,
  `MINCODEINSUBSECTION` mediumint UNSIGNED NOT NULL,
  `MAXCODEINSUBSECTION` mediumint UNSIGNED NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `D_ICD_DIAGNOSES` (
  `ROW_ID` mediumint UNSIGNED NOT NULL,
  `ICD9_CODE` varchar(10) NOT NULL,
  `SHORT_TITLE` varchar(50) NOT NULL,
  `LONG_TITLE` varchar(255) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `D_ICD_PROCEDURES` (
  `ROW_ID` mediumint UNSIGNED NOT NULL,
  `ICD9_CODE` varchar(10) NOT NULL,
  `SHORT_TITLE` varchar(50) NOT NULL,
  `LONG_TITLE` varchar(255) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `D_ITEMS` (
  `ROW_ID` mediumint UNSIGNED NOT NULL,
  `ITEMID` mediumint UNSIGNED NOT NULL,
  `LABEL` varchar(200) DEFAULT NULL,
  `ABBREVIATION` varchar(100) DEFAULT NULL,
  `DBSOURCE` varchar(20) NOT NULL,
  `LINKSTO` varchar(50) DEFAULT NULL,
  `CATEGORY` varchar(100) DEFAULT NULL,
  `UNITNAME` varchar(100) DEFAULT NULL,
  `PARAM_TYPE` varchar(30) DEFAULT NULL,
  `CONCEPTID` int DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `D_LABITEMS` (
  `ROW_ID` mediumint UNSIGNED NOT NULL,
  `ITEMID` smallint UNSIGNED NOT NULL,
  `LABEL` varchar(100) NOT NULL,
  `FLUID` varchar(100) NOT NULL,
  `CATEGORY` varchar(100) NOT NULL,
  `LOINC_CODE` varchar(100) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `echo_reports` (
  `ROW_ID` int UNSIGNED NOT NULL,
  `SUBJECT_ID` mediumint UNSIGNED NOT NULL,
  `HADM_ID` mediumint UNSIGNED DEFAULT NULL,
  `CHARTDATE` date NOT NULL,
  `CHARTTIME` datetime DEFAULT NULL,
  `STORETIME` datetime DEFAULT NULL,
  `CATEGORY` varchar(50) CHARACTER SET utf8 NOT NULL,
  `DESCRIPTION` varchar(255) CHARACTER SET utf8 NOT NULL,
  `CGID` smallint UNSIGNED DEFAULT NULL,
  `ISERROR` tinyint UNSIGNED DEFAULT NULL,
  `TEXT` mediumtext CHARACTER SET utf8,
  `Impression` varchar(2048) DEFAULT NULL,
  `acd_study_note` tinyint(1) NOT NULL,
  `fhir_json` mediumtext CHARACTER SET utf8
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `ekg_reports` (
  `ROW_ID` int UNSIGNED NOT NULL,
  `SUBJECT_ID` mediumint UNSIGNED NOT NULL,
  `HADM_ID` mediumint UNSIGNED DEFAULT NULL,
  `CHARTDATE` date NOT NULL,
  `CHARTTIME` datetime DEFAULT NULL,
  `STORETIME` datetime DEFAULT NULL,
  `CATEGORY` varchar(50) CHARACTER SET utf8 NOT NULL,
  `DESCRIPTION` varchar(255) CHARACTER SET utf8 NOT NULL,
  `CGID` smallint UNSIGNED DEFAULT NULL,
  `ISERROR` tinyint UNSIGNED DEFAULT NULL,
  `TEXT` mediumtext CHARACTER SET utf8,
  `acd_study_note` tinyint(1) NOT NULL,
  `fhir_json` mediumtext CHARACTER SET utf8
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `ICUSTAYS` (
  `ROW_ID` mediumint UNSIGNED NOT NULL,
  `SUBJECT_ID` mediumint UNSIGNED NOT NULL,
  `HADM_ID` mediumint UNSIGNED NOT NULL,
  `ICUSTAY_ID` mediumint UNSIGNED NOT NULL,
  `DBSOURCE` varchar(20) NOT NULL,
  `FIRST_CAREUNIT` varchar(20) NOT NULL,
  `LAST_CAREUNIT` varchar(20) NOT NULL,
  `FIRST_WARDID` tinyint UNSIGNED NOT NULL,
  `LAST_WARDID` tinyint UNSIGNED NOT NULL,
  `INTIME` datetime NOT NULL,
  `OUTTIME` datetime DEFAULT NULL,
  `LOS` decimal(22,10) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `INPUTEVENTS_CV` (
  `ROW_ID` int UNSIGNED NOT NULL,
  `SUBJECT_ID` mediumint UNSIGNED NOT NULL,
  `HADM_ID` mediumint UNSIGNED DEFAULT NULL,
  `ICUSTAY_ID` mediumint UNSIGNED DEFAULT NULL,
  `CHARTTIME` datetime NOT NULL,
  `ITEMID` smallint UNSIGNED NOT NULL,
  `AMOUNT` decimal(22,10) DEFAULT NULL,
  `AMOUNTUOM` varchar(30) DEFAULT NULL,
  `RATE` decimal(22,10) DEFAULT NULL,
  `RATEUOM` varchar(30) DEFAULT NULL,
  `STORETIME` datetime NOT NULL,
  `CGID` smallint UNSIGNED DEFAULT NULL,
  `ORDERID` mediumint UNSIGNED NOT NULL,
  `LINKORDERID` mediumint UNSIGNED NOT NULL,
  `STOPPED` varchar(30) DEFAULT NULL,
  `NEWBOTTLE` tinyint UNSIGNED DEFAULT NULL,
  `ORIGINALAMOUNT` decimal(22,10) DEFAULT NULL,
  `ORIGINALAMOUNTUOM` varchar(30) DEFAULT NULL,
  `ORIGINALROUTE` varchar(30) DEFAULT NULL,
  `ORIGINALRATE` decimal(22,10) DEFAULT NULL,
  `ORIGINALRATEUOM` varchar(30) DEFAULT NULL,
  `ORIGINALSITE` varchar(30) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `INPUTEVENTS_MV` (
  `ROW_ID` mediumint UNSIGNED NOT NULL,
  `SUBJECT_ID` mediumint UNSIGNED NOT NULL,
  `HADM_ID` mediumint UNSIGNED NOT NULL,
  `ICUSTAY_ID` mediumint UNSIGNED DEFAULT NULL,
  `STARTTIME` datetime NOT NULL,
  `ENDTIME` datetime NOT NULL,
  `ITEMID` mediumint UNSIGNED NOT NULL,
  `AMOUNT` decimal(22,10) NOT NULL,
  `AMOUNTUOM` varchar(30) NOT NULL,
  `RATE` decimal(22,10) DEFAULT NULL,
  `RATEUOM` varchar(30) DEFAULT NULL,
  `STORETIME` datetime NOT NULL,
  `CGID` smallint UNSIGNED NOT NULL,
  `ORDERID` mediumint UNSIGNED NOT NULL,
  `LINKORDERID` mediumint UNSIGNED NOT NULL,
  `ORDERCATEGORYNAME` varchar(100) NOT NULL,
  `SECONDARYORDERCATEGORYNAME` varchar(100) DEFAULT NULL,
  `ORDERCOMPONENTTYPEDESCRIPTION` varchar(20) NOT NULL,
  `ORDERCATEGORYDESCRIPTION` varchar(50) NOT NULL,
  `PATIENTWEIGHT` decimal(22,10) NOT NULL,
  `TOTALAMOUNT` decimal(22,10) DEFAULT NULL,
  `TOTALAMOUNTUOM` varchar(255) DEFAULT NULL,
  `ISOPENBAG` tinyint UNSIGNED NOT NULL,
  `CONTINUEINNEXTDEPT` tinyint UNSIGNED NOT NULL,
  `CANCELREASON` tinyint UNSIGNED NOT NULL,
  `STATUSDESCRIPTION` varchar(30) NOT NULL,
  `COMMENTS_EDITEDBY` varchar(30) DEFAULT NULL,
  `COMMENTS_CANCELEDBY` varchar(30) DEFAULT NULL,
  `COMMENTS_DATE` datetime DEFAULT NULL,
  `ORIGINALAMOUNT` decimal(22,10) NOT NULL,
  `ORIGINALRATE` decimal(22,10) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `LABEVENTS` (
  `ROW_ID` int UNSIGNED NOT NULL,
  `SUBJECT_ID` mediumint UNSIGNED NOT NULL,
  `HADM_ID` mediumint UNSIGNED DEFAULT NULL,
  `ITEMID` smallint UNSIGNED NOT NULL,
  `CHARTTIME` datetime NOT NULL,
  `VALUE` varchar(200) DEFAULT NULL,
  `VALUENUM` decimal(22,10) DEFAULT NULL,
  `VALUEUOM` varchar(20) DEFAULT NULL,
  `FLAG` varchar(20) DEFAULT NULL,
  `acd_study` tinyint(1) NOT NULL DEFAULT '0',
  `fhir_json` varchar(2000) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `medication_adverse_event` (
  `id` int NOT NULL,
  `note_row_id` int NOT NULL,
  `hadm_id` int NOT NULL,
  `ade_drug_name` varchar(256) NOT NULL,
  `rx_norm_id` varchar(16) NOT NULL,
  `ade_reaction` varchar(256) NOT NULL,
  `start_index` int NOT NULL,
  `end_index` int NOT NULL,
  `ade_score` float NOT NULL,
  `ade_valid` tinyint(1) NOT NULL,
  `ade_span` varchar(4096) NOT NULL,
  `ambiguous_phrase` tinyint(1) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='table to extract the ADEs from NoteEvents';

CREATE TABLE `merged_diagnoses` (
  `Row_ID` mediumint UNSIGNED NOT NULL,
  `SUBJECT_ID` mediumint UNSIGNED NOT NULL,
  `HADM_ID` mediumint UNSIGNED NOT NULL,
  `SEQ_NUM` tinyint UNSIGNED DEFAULT NULL,
  `ICD9_CODE` varchar(10) CHARACTER SET utf8 NOT NULL,
  `short_title` varchar(50) CHARACTER SET utf8 NOT NULL,
  `long_title` varchar(255) CHARACTER SET utf8 NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `MICROBIOLOGYEVENTS` (
  `ROW_ID` mediumint UNSIGNED NOT NULL,
  `SUBJECT_ID` mediumint UNSIGNED NOT NULL,
  `HADM_ID` mediumint UNSIGNED DEFAULT NULL,
  `CHARTDATE` datetime NOT NULL,
  `CHARTTIME` datetime DEFAULT NULL,
  `SPEC_ITEMID` mediumint UNSIGNED DEFAULT NULL,
  `SPEC_TYPE_DESC` varchar(100) NOT NULL,
  `ORG_ITEMID` mediumint UNSIGNED DEFAULT NULL,
  `ORG_NAME` varchar(100) DEFAULT NULL,
  `ISOLATE_NUM` tinyint UNSIGNED DEFAULT NULL,
  `AB_ITEMID` mediumint UNSIGNED DEFAULT NULL,
  `AB_NAME` varchar(30) DEFAULT NULL,
  `DILUTION_TEXT` varchar(10) DEFAULT NULL,
  `DILUTION_COMPARISON` varchar(20) DEFAULT NULL,
  `DILUTION_VALUE` smallint UNSIGNED DEFAULT NULL,
  `INTERPRETATION` varchar(5) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `microbiology_reports` (
  `ROW_ID` int NOT NULL,
  `SUBJECT_ID` int NOT NULL,
  `HADM_ID` int NOT NULL,
  `CHARTDATE` datetime NOT NULL,
  `SPEC_ITEMID` int DEFAULT NULL,
  `SPEC_TYPE_DESC` varchar(64) NOT NULL,
  `ORG_ITEMID` int NOT NULL,
  `ORG_NAME` varchar(128) NOT NULL,
  `TEXT` text CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL,
  `fhir_json` varchar(4096) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='Collated microbiology reports';

CREATE TABLE `noteevents` (
  `ROW_ID` int UNSIGNED NOT NULL,
  `SUBJECT_ID` mediumint UNSIGNED NOT NULL,
  `HADM_ID` mediumint UNSIGNED DEFAULT NULL,
  `CHARTDATE` date NOT NULL,
  `CHARTTIME` datetime DEFAULT NULL,
  `STORETIME` datetime DEFAULT NULL,
  `CATEGORY` varchar(50) NOT NULL,
  `DESCRIPTION` varchar(255) NOT NULL,
  `CGID` smallint UNSIGNED DEFAULT NULL,
  `ISERROR` tinyint UNSIGNED DEFAULT NULL,
  `TEXT` mediumtext,
  `acd_study_note` tinyint(1) NOT NULL,
  `fhir_json` mediumtext
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `OUTPUTEVENTS` (
  `ROW_ID` mediumint UNSIGNED NOT NULL,
  `SUBJECT_ID` mediumint UNSIGNED NOT NULL,
  `HADM_ID` mediumint UNSIGNED DEFAULT NULL,
  `ICUSTAY_ID` mediumint UNSIGNED DEFAULT NULL,
  `CHARTTIME` datetime NOT NULL,
  `ITEMID` mediumint UNSIGNED NOT NULL,
  `VALUE` decimal(22,10) DEFAULT NULL,
  `VALUEUOM` varchar(30) DEFAULT NULL,
  `STORETIME` datetime NOT NULL,
  `CGID` smallint UNSIGNED NOT NULL,
  `STOPPED` varchar(30) DEFAULT NULL,
  `NEWBOTTLE` char(1) DEFAULT NULL,
  `ISERROR` tinyint UNSIGNED DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `pathways` (
  `id` int NOT NULL,
  `name` varchar(128) NOT NULL,
  `description` varchar(512) NOT NULL,
  `activatingattributecode` varchar(128) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `pathway_treatments` (
  `id` int NOT NULL,
  `type` varchar(128) NOT NULL,
  `pathway_id` int NOT NULL,
  `description` varchar(512) NOT NULL,
  `action_to_do` varchar(32) NOT NULL,
  `concept_id` varchar(128) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `PATIENTS` (
  `ROW_ID` mediumint UNSIGNED NOT NULL,
  `SUBJECT_ID` mediumint UNSIGNED NOT NULL,
  `first_name` varchar(128) NOT NULL,
  `last_name` varchar(128) NOT NULL,
  `street` varchar(256) NOT NULL,
  `city` varchar(256) NOT NULL,
  `state` varchar(2) NOT NULL,
  `zip` varchar(10) NOT NULL,
  `GENDER` varchar(5) NOT NULL,
  `race` varchar(32) NOT NULL,
  `language` varchar(32) NOT NULL,
  `ethnicity` varchar(64) NOT NULL,
  `religion` varchar(32) NOT NULL,
  `marital_status` varchar(64) NOT NULL,
  `insurance` varchar(64) NOT NULL,
  `DOB` date NOT NULL,
  `DOD` date DEFAULT NULL,
  `DOD_HOSP` date DEFAULT NULL,
  `EXPIRE_FLAG` tinyint UNSIGNED NOT NULL,
  `acd_study_patient` tinyint(1) NOT NULL DEFAULT '0',
  `fhir_json` varchar(2048) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `PRESCRIPTIONS` (
  `ROW_ID` mediumint UNSIGNED NOT NULL,
  `SUBJECT_ID` mediumint UNSIGNED NOT NULL,
  `HADM_ID` mediumint UNSIGNED NOT NULL,
  `ICUSTAY_ID` mediumint UNSIGNED DEFAULT NULL,
  `STARTDATE` datetime DEFAULT NULL,
  `ENDDATE` datetime DEFAULT NULL,
  `DRUG_TYPE` varchar(100) NOT NULL,
  `DRUG` varchar(100) DEFAULT NULL,
  `DRUG_NAME_POE` varchar(100) DEFAULT NULL,
  `DRUG_NAME_GENERIC` varchar(100) DEFAULT NULL,
  `FORMULARY_DRUG_CD` varchar(120) DEFAULT NULL,
  `GSN` varchar(200) DEFAULT NULL,
  `NDC` varchar(120) DEFAULT NULL,
  `rxNormId` varchar(32) NOT NULL,
  `PROD_STRENGTH` varchar(120) DEFAULT NULL,
  `DOSE_VAL_RX` varchar(120) DEFAULT NULL,
  `DOSE_UNIT_RX` varchar(120) DEFAULT NULL,
  `FORM_VAL_DISP` varchar(120) DEFAULT NULL,
  `FORM_UNIT_DISP` varchar(120) DEFAULT NULL,
  `ROUTE` varchar(120) DEFAULT NULL,
  `acd_study_med` tinyint(1) NOT NULL,
  `fhir_json` varchar(2048) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `PROCEDUREEVENTS_MV` (
  `ROW_ID` mediumint UNSIGNED NOT NULL,
  `SUBJECT_ID` mediumint UNSIGNED NOT NULL,
  `HADM_ID` mediumint UNSIGNED NOT NULL,
  `ICUSTAY_ID` mediumint UNSIGNED DEFAULT NULL,
  `STARTTIME` datetime NOT NULL,
  `ENDTIME` datetime NOT NULL,
  `ITEMID` mediumint UNSIGNED NOT NULL,
  `VALUE` decimal(22,10) NOT NULL,
  `VALUEUOM` varchar(30) NOT NULL,
  `LOCATION` varchar(30) DEFAULT NULL,
  `LOCATIONCATEGORY` varchar(30) DEFAULT NULL,
  `STORETIME` datetime NOT NULL,
  `CGID` smallint UNSIGNED NOT NULL,
  `ORDERID` mediumint UNSIGNED NOT NULL,
  `LINKORDERID` mediumint UNSIGNED NOT NULL,
  `ORDERCATEGORYNAME` varchar(100) NOT NULL,
  `SECONDARYORDERCATEGORYNAME` varchar(100) DEFAULT NULL,
  `ORDERCATEGORYDESCRIPTION` varchar(50) NOT NULL,
  `ISOPENBAG` tinyint(1) NOT NULL,
  `CONTINUEINNEXTDEPT` tinyint UNSIGNED NOT NULL,
  `CANCELREASON` tinyint UNSIGNED NOT NULL,
  `STATUSDESCRIPTION` varchar(30) NOT NULL,
  `COMMENTS_EDITEDBY` varchar(30) DEFAULT NULL,
  `COMMENTS_CANCELEDBY` varchar(30) DEFAULT NULL,
  `COMMENTS_DATE` datetime DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `PROCEDURES_ICD` (
  `ROW_ID` mediumint UNSIGNED NOT NULL,
  `SUBJECT_ID` mediumint UNSIGNED NOT NULL,
  `HADM_ID` mediumint UNSIGNED NOT NULL,
  `SEQ_NUM` tinyint UNSIGNED NOT NULL,
  `ICD9_CODE` varchar(10) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `radiology_reports` (
  `ROW_ID` int UNSIGNED NOT NULL,
  `SUBJECT_ID` mediumint UNSIGNED NOT NULL,
  `HADM_ID` mediumint UNSIGNED DEFAULT NULL,
  `CHARTDATE` date NOT NULL,
  `CHARTTIME` datetime DEFAULT NULL,
  `STORETIME` datetime DEFAULT NULL,
  `CATEGORY` varchar(50) CHARACTER SET utf8 NOT NULL,
  `DESCRIPTION` varchar(255) CHARACTER SET utf8 NOT NULL,
  `CGID` smallint UNSIGNED DEFAULT NULL,
  `ISERROR` tinyint UNSIGNED DEFAULT NULL,
  `TEXT` mediumtext CHARACTER SET utf8,
  `Impression` varchar(2048) DEFAULT NULL,
  `acd_study_note` tinyint(1) NOT NULL,
  `fhir_json` mediumtext CHARACTER SET utf8
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `SERVICES` (
  `ROW_ID` mediumint UNSIGNED NOT NULL,
  `SUBJECT_ID` mediumint UNSIGNED NOT NULL,
  `HADM_ID` mediumint UNSIGNED NOT NULL,
  `TRANSFERTIME` datetime NOT NULL,
  `PREV_SERVICE` varchar(20) DEFAULT NULL,
  `CURR_SERVICE` varchar(20) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `social_history` (
  `subject_id` varchar(128) NOT NULL,
  `text` mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL,
  `hadm_id` int NOT NULL,
  `note_description` varchar(256) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `TRANSFERS` (
  `ROW_ID` mediumint UNSIGNED NOT NULL,
  `SUBJECT_ID` mediumint UNSIGNED NOT NULL,
  `HADM_ID` mediumint UNSIGNED NOT NULL,
  `ICUSTAY_ID` mediumint UNSIGNED DEFAULT NULL,
  `DBSOURCE` varchar(20) DEFAULT NULL,
  `EVENTTYPE` varchar(20) DEFAULT NULL,
  `PREV_CAREUNIT` varchar(20) DEFAULT NULL,
  `CURR_CAREUNIT` varchar(20) DEFAULT NULL,
  `PREV_WARDID` tinyint UNSIGNED DEFAULT NULL,
  `CURR_WARDID` tinyint UNSIGNED DEFAULT NULL,
  `INTIME` datetime DEFAULT NULL,
  `OUTTIME` datetime DEFAULT NULL,
  `LOS` decimal(22,10) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


ALTER TABLE `ADMISSIONS`
  ADD PRIMARY KEY (`ROW_ID`),
  ADD UNIQUE KEY `ADMISSIONS_HADM_ID` (`HADM_ID`),
  ADD KEY `ADMISSIONS_IDX01` (`SUBJECT_ID`,`HADM_ID`),
  ADD KEY `ADMISSIONS_IDX02` (`ADMITTIME`,`DISCHTIME`,`DEATHTIME`),
  ADD KEY `ADMISSIONS_IDX03` (`ADMISSION_TYPE`),
  ADD KEY `LENGTH_OF_STAY` (`LENGTH_OF_STAY`);

ALTER TABLE `CALLOUT`
  ADD PRIMARY KEY (`ROW_ID`),
  ADD UNIQUE KEY `CALLOUT_CURRENTRESERVATIONTIME` (`CURRENTRESERVATIONTIME`),
  ADD KEY `CALLOUT_IDX01` (`SUBJECT_ID`,`HADM_ID`),
  ADD KEY `CALLOUT_IDX02` (`CURR_CAREUNIT`),
  ADD KEY `CALLOUT_IDX03` (`CALLOUT_SERVICE`),
  ADD KEY `CALLOUT_IDX04` (`CURR_WARDID`,`CALLOUT_WARDID`,`DISCHARGE_WARDID`),
  ADD KEY `CALLOUT_IDX05` (`CALLOUT_STATUS`,`CALLOUT_OUTCOME`),
  ADD KEY `CALLOUT_IDX06` (`CREATETIME`,`UPDATETIME`,`ACKNOWLEDGETIME`,`OUTCOMETIME`),
  ADD KEY `callout_fk_hadm_id` (`HADM_ID`);

ALTER TABLE `CAREGIVERS`
  ADD PRIMARY KEY (`ROW_ID`),
  ADD UNIQUE KEY `CAREGIVERS_CGID` (`CGID`),
  ADD KEY `CAREGIVERS_IDX01` (`CGID`,`LABEL`),
  ADD KEY `first_name` (`first_name`),
  ADD KEY `last name` (`last_name`),
  ADD KEY `gender` (`gender`),
  ADD KEY `npinumber` (`NPI_number`);

ALTER TABLE `chartevents`
  ADD PRIMARY KEY (`ROW_ID`),
  ADD KEY `CHARTEVENTS_idx01` (`SUBJECT_ID`,`HADM_ID`,`ICUSTAY_ID`),
  ADD KEY `CHARTEVENTS_idx02` (`ITEMID`),
  ADD KEY `CHARTEVENTS_idx03` (`CHARTTIME`,`STORETIME`),
  ADD KEY `CHARTEVENTS_idx04` (`CGID`);

ALTER TABLE `CPTEVENTS`
  ADD PRIMARY KEY (`ROW_ID`),
  ADD KEY `CPTEVENTS_idx01` (`SUBJECT_ID`,`HADM_ID`),
  ADD KEY `CPTEVENTS_idx02` (`CPT_CD`,`TICKET_ID_SEQ`),
  ADD KEY `cptevents_fk_hadm_id` (`HADM_ID`),
  ADD KEY `DESCRIPTION` (`DESCRIPTION`);
ALTER TABLE `CPTEVENTS` ADD FULLTEXT KEY `DESCRIPTION_2` (`DESCRIPTION`);

ALTER TABLE `DATETIMEEVENTS`
  ADD PRIMARY KEY (`ROW_ID`),
  ADD KEY `DATETIMEEVENTS_idx01` (`SUBJECT_ID`,`HADM_ID`,`ICUSTAY_ID`),
  ADD KEY `DATETIMEEVENTS_idx02` (`ITEMID`),
  ADD KEY `DATETIMEEVENTS_idx03` (`CHARTTIME`),
  ADD KEY `DATETIMEEVENTS_idx04` (`CGID`),
  ADD KEY `DATETIMEEVENTS_idx05` (`VALUE`),
  ADD KEY `datetimeevents_fk_hadm_id` (`HADM_ID`),
  ADD KEY `datetimeevents_fk_icustay_id` (`ICUSTAY_ID`);

ALTER TABLE `DIAGNOSES_ICD`
  ADD PRIMARY KEY (`ROW_ID`),
  ADD KEY `DIAGNOSES_ICD_idx01` (`SUBJECT_ID`,`HADM_ID`),
  ADD KEY `DIAGNOSES_ICD_idx02` (`ICD9_CODE`,`SEQ_NUM`),
  ADD KEY `diagnoses_icd_fk_hadm_id` (`HADM_ID`);

ALTER TABLE `DRGCODES`
  ADD PRIMARY KEY (`ROW_ID`),
  ADD KEY `DRGCODES_idx01` (`SUBJECT_ID`,`HADM_ID`),
  ADD KEY `DRGCODES_idx02` (`DRG_CODE`,`DRG_TYPE`),
  ADD KEY `DRGCODES_idx03` (`DESCRIPTION`,`DRG_SEVERITY`),
  ADD KEY `drgcodes_fk_hadm_id` (`HADM_ID`);
ALTER TABLE `DRGCODES` ADD FULLTEXT KEY `DESCRIPTION` (`DESCRIPTION`);

ALTER TABLE `D_CPT`
  ADD PRIMARY KEY (`ROW_ID`),
  ADD UNIQUE KEY `D_CPT_SUBSECTIONRANGE` (`SUBSECTIONRANGE`),
  ADD UNIQUE KEY `D_CPT_MAXCODEINSUBSECTION` (`MAXCODEINSUBSECTION`);

ALTER TABLE `D_ICD_DIAGNOSES`
  ADD PRIMARY KEY (`ROW_ID`),
  ADD UNIQUE KEY `D_ICD_DIAGNOSES_ICD9_CODE` (`ICD9_CODE`),
  ADD KEY `D_ICD_DIAG_idx02` (`SHORT_TITLE`),
  ADD KEY `ICD9_CODE` (`ICD9_CODE`);

ALTER TABLE `D_ICD_PROCEDURES`
  ADD PRIMARY KEY (`ROW_ID`),
  ADD UNIQUE KEY `D_ICD_PROCEDURES_ICD9_CODE` (`ICD9_CODE`),
  ADD UNIQUE KEY `D_ICD_PROCEDURES_SHORT_TITLE` (`SHORT_TITLE`);

ALTER TABLE `D_ITEMS`
  ADD PRIMARY KEY (`ROW_ID`),
  ADD UNIQUE KEY `D_ITEMS_ITEMID` (`ITEMID`),
  ADD KEY `D_ITEMS_idx02` (`LABEL`,`DBSOURCE`),
  ADD KEY `D_ITEMS_idx03` (`CATEGORY`);

ALTER TABLE `D_LABITEMS`
  ADD PRIMARY KEY (`ROW_ID`),
  ADD UNIQUE KEY `D_LABITEMS_ITEMID` (`ITEMID`),
  ADD KEY `D_LABITEMS_idx02` (`LABEL`,`FLUID`,`CATEGORY`),
  ADD KEY `D_LABITEMS_idx03` (`LOINC_CODE`);

ALTER TABLE `echo_reports`
  ADD PRIMARY KEY (`ROW_ID`),
  ADD KEY `SUBJECT_ID` (`SUBJECT_ID`),
  ADD KEY `CHARTDATE` (`CHARTDATE`);
ALTER TABLE `echo_reports` ADD FULLTEXT KEY `TEXT` (`TEXT`);
ALTER TABLE `echo_reports` ADD FULLTEXT KEY `Impression` (`Impression`);

ALTER TABLE `ekg_reports`
  ADD PRIMARY KEY (`ROW_ID`),
  ADD KEY `SUBJECT_ID` (`SUBJECT_ID`),
  ADD KEY `CHARTDATE` (`CHARTDATE`);
ALTER TABLE `ekg_reports` ADD FULLTEXT KEY `TEXT` (`TEXT`);

ALTER TABLE `ICUSTAYS`
  ADD PRIMARY KEY (`ROW_ID`),
  ADD UNIQUE KEY `ICUSTAYS_ICUSTAY_ID` (`ICUSTAY_ID`),
  ADD KEY `ICUSTAYS_idx01` (`SUBJECT_ID`,`HADM_ID`),
  ADD KEY `ICUSTAYS_idx02` (`ICUSTAY_ID`,`DBSOURCE`),
  ADD KEY `ICUSTAYS_idx03` (`LOS`),
  ADD KEY `ICUSTAYS_idx04` (`FIRST_CAREUNIT`),
  ADD KEY `ICUSTAYS_idx05` (`LAST_CAREUNIT`),
  ADD KEY `icustays_fk_hadm_id` (`HADM_ID`),
  ADD KEY `INTIME` (`INTIME`),
  ADD KEY `INTIME_2` (`INTIME`),
  ADD KEY `LOS` (`LOS`);

ALTER TABLE `INPUTEVENTS_CV`
  ADD PRIMARY KEY (`ROW_ID`),
  ADD KEY `INPUTEVENTS_CV_idx01` (`SUBJECT_ID`,`HADM_ID`),
  ADD KEY `INPUTEVENTS_CV_idx03` (`CHARTTIME`,`STORETIME`),
  ADD KEY `INPUTEVENTS_CV_idx04` (`ITEMID`),
  ADD KEY `INPUTEVENTS_CV_idx05` (`RATE`),
  ADD KEY `INPUTEVENTS_CV_idx06` (`AMOUNT`),
  ADD KEY `INPUTEVENTS_CV_idx07` (`CGID`),
  ADD KEY `INPUTEVENTS_CV_idx08` (`LINKORDERID`,`ORDERID`),
  ADD KEY `inputevents_cv_fk_hadm_id` (`HADM_ID`),
  ADD KEY `inputevents_cv_fk_icustay_id` (`ICUSTAY_ID`);

ALTER TABLE `INPUTEVENTS_MV`
  ADD PRIMARY KEY (`ROW_ID`),
  ADD KEY `INPUTEVENTS_MV_idx01` (`SUBJECT_ID`,`HADM_ID`),
  ADD KEY `INPUTEVENTS_MV_idx02` (`ICUSTAY_ID`),
  ADD KEY `INPUTEVENTS_MV_idx03` (`ENDTIME`,`STARTTIME`),
  ADD KEY `INPUTEVENTS_MV_idx04` (`ITEMID`),
  ADD KEY `INPUTEVENTS_MV_idx05` (`RATE`),
  ADD KEY `INPUTEVENTS_MV_idx06` (`AMOUNT`),
  ADD KEY `INPUTEVENTS_MV_idx07` (`CGID`),
  ADD KEY `INPUTEVENTS_MV_idx08` (`LINKORDERID`,`ORDERID`),
  ADD KEY `inputevents_mv_fk_hadm_id` (`HADM_ID`);

ALTER TABLE `LABEVENTS`
  ADD PRIMARY KEY (`ROW_ID`),
  ADD KEY `LABEVENTS_idx01` (`SUBJECT_ID`,`HADM_ID`),
  ADD KEY `LABEVENTS_idx02` (`ITEMID`),
  ADD KEY `LABEVENTS_idx03` (`CHARTTIME`),
  ADD KEY `LABEVENTS_idx04` (`VALUE`,`VALUENUM`),
  ADD KEY `labevents_fk_hadm_id` (`HADM_ID`),
  ADD KEY `acd_study` (`acd_study`),
  ADD KEY `acdnonzero` (`acd_study`,`VALUENUM`) USING BTREE;

ALTER TABLE `medication_adverse_event`
  ADD PRIMARY KEY (`id`),
  ADD KEY `note_row_id` (`note_row_id`),
  ADD KEY `hadm_id` (`hadm_id`),
  ADD KEY `rx_norm_id` (`rx_norm_id`),
  ADD KEY `ambiguous_phrase` (`ambiguous_phrase`);
ALTER TABLE `medication_adverse_event` ADD FULLTEXT KEY `ade_span` (`ade_span`);

ALTER TABLE `merged_diagnoses`
  ADD PRIMARY KEY (`Row_ID`) USING BTREE,
  ADD KEY `subject` (`SUBJECT_ID`) USING BTREE,
  ADD KEY `icd` (`ICD9_CODE`) USING BTREE;

ALTER TABLE `MICROBIOLOGYEVENTS`
  ADD PRIMARY KEY (`ROW_ID`),
  ADD KEY `MICROBIOLOGYEVENTS_idx01` (`SUBJECT_ID`,`HADM_ID`),
  ADD KEY `MICROBIOLOGYEVENTS_idx02` (`CHARTDATE`,`CHARTTIME`),
  ADD KEY `MICROBIOLOGYEVENTS_idx03` (`SPEC_ITEMID`,`ORG_ITEMID`,`AB_ITEMID`),
  ADD KEY `microbiologyevents_fk_hadm_id` (`HADM_ID`);

ALTER TABLE `microbiology_reports`
  ADD PRIMARY KEY (`ROW_ID`),
  ADD KEY `SUBJECT_ID` (`SUBJECT_ID`),
  ADD KEY `HADM_ID` (`HADM_ID`),
  ADD KEY `SPEC_TYPE_DESC` (`SPEC_TYPE_DESC`),
  ADD KEY `ORG_NAME` (`ORG_NAME`),
  ADD KEY `CHARTDATE` (`CHARTDATE`);
ALTER TABLE `microbiology_reports` ADD FULLTEXT KEY `TEXT` (`TEXT`);

ALTER TABLE `noteevents`
  ADD PRIMARY KEY (`ROW_ID`),
  ADD KEY `NOTEEVENTS_idx01` (`SUBJECT_ID`,`HADM_ID`),
  ADD KEY `NOTEEVENTS_idx02` (`CHARTDATE`),
  ADD KEY `NOTEEVENTS_idx03` (`CGID`),
  ADD KEY `NOTEEVENTS_idx05` (`CATEGORY`,`DESCRIPTION`),
  ADD KEY `noteevents_fk_hadm_id` (`HADM_ID`),
  ADD KEY `CATEGORY` (`CATEGORY`),
  ADD KEY `description` (`DESCRIPTION`) USING BTREE,
  ADD KEY `acd_study_note` (`acd_study_note`),
  ADD KEY `SUBJECT_ID` (`SUBJECT_ID`);

ALTER TABLE `OUTPUTEVENTS`
  ADD PRIMARY KEY (`ROW_ID`),
  ADD KEY `OUTPUTEVENTS_idx01` (`SUBJECT_ID`,`HADM_ID`),
  ADD KEY `OUTPUTEVENTS_idx02` (`ICUSTAY_ID`),
  ADD KEY `OUTPUTEVENTS_idx03` (`CHARTTIME`,`STORETIME`),
  ADD KEY `OUTPUTEVENTS_idx04` (`ITEMID`),
  ADD KEY `OUTPUTEVENTS_idx05` (`VALUE`),
  ADD KEY `OUTPUTEVENTS_idx06` (`CGID`),
  ADD KEY `outputevents_fk_hadm_id` (`HADM_ID`);

ALTER TABLE `pathways`
  ADD PRIMARY KEY (`id`),
  ADD KEY `name` (`name`),
  ADD KEY `activatingattributecode` (`activatingattributecode`);

ALTER TABLE `pathway_treatments`
  ADD PRIMARY KEY (`id`),
  ADD KEY `type` (`type`),
  ADD KEY `action_to_do` (`action_to_do`),
  ADD KEY `concept_id` (`concept_id`),
  ADD KEY `pathway_id` (`pathway_id`);

ALTER TABLE `PATIENTS`
  ADD PRIMARY KEY (`ROW_ID`),
  ADD UNIQUE KEY `PATIENTS_SUBJECT_ID` (`SUBJECT_ID`),
  ADD KEY `PATIENTS_idx01` (`EXPIRE_FLAG`),
  ADD KEY `first_name` (`first_name`),
  ADD KEY `last_name` (`last_name`),
  ADD KEY `state` (`state`),
  ADD KEY `zip` (`zip`),
  ADD KEY `acd_study_patient` (`acd_study_patient`),
  ADD KEY `race` (`race`),
  ADD KEY `language` (`language`),
  ADD KEY `religion` (`religion`),
  ADD KEY `marital_status` (`marital_status`),
  ADD KEY `insurance` (`insurance`),
  ADD KEY `religion_2` (`religion`),
  ADD KEY `language_2` (`language`),
  ADD KEY `ethnicity` (`ethnicity`),
  ADD KEY `DOB` (`DOB`);

ALTER TABLE `PRESCRIPTIONS`
  ADD PRIMARY KEY (`ROW_ID`),
  ADD KEY `PRESCRIPTIONS_idx01` (`SUBJECT_ID`,`HADM_ID`),
  ADD KEY `PRESCRIPTIONS_idx02` (`ICUSTAY_ID`),
  ADD KEY `PRESCRIPTIONS_idx03` (`DRUG_TYPE`),
  ADD KEY `PRESCRIPTIONS_idx04` (`DRUG`),
  ADD KEY `PRESCRIPTIONS_idx05` (`STARTDATE`,`ENDDATE`),
  ADD KEY `prescriptions_fk_hadm_id` (`HADM_ID`),
  ADD KEY `ndccode` (`NDC`) USING BTREE,
  ADD KEY `RxNorm` (`rxNormId`),
  ADD KEY `acd_study_med` (`acd_study_med`),
  ADD KEY `STARTDATE` (`STARTDATE`);

ALTER TABLE `PROCEDUREEVENTS_MV`
  ADD PRIMARY KEY (`ROW_ID`),
  ADD UNIQUE KEY `PROCEDUREEVENTS_MV_ORDERID` (`ORDERID`),
  ADD KEY `PROCEDUREEVENTS_MV_idx01` (`SUBJECT_ID`,`HADM_ID`),
  ADD KEY `PROCEDUREEVENTS_MV_idx02` (`ICUSTAY_ID`),
  ADD KEY `PROCEDUREEVENTS_MV_idx03` (`ITEMID`),
  ADD KEY `PROCEDUREEVENTS_MV_idx04` (`CGID`),
  ADD KEY `PROCEDUREEVENTS_MV_idx05` (`ORDERCATEGORYNAME`),
  ADD KEY `procedureevents_mv_fk_hadm_id` (`HADM_ID`);

ALTER TABLE `PROCEDURES_ICD`
  ADD PRIMARY KEY (`ROW_ID`),
  ADD KEY `PROCEDURES_ICD_idx01` (`SUBJECT_ID`,`HADM_ID`),
  ADD KEY `PROCEDURES_ICD_idx02` (`ICD9_CODE`,`SEQ_NUM`),
  ADD KEY `procedures_icd_fk_hadm_id` (`HADM_ID`);

ALTER TABLE `radiology_reports`
  ADD PRIMARY KEY (`ROW_ID`);
ALTER TABLE `radiology_reports` ADD FULLTEXT KEY `Impression` (`Impression`);

ALTER TABLE `SERVICES`
  ADD PRIMARY KEY (`ROW_ID`),
  ADD KEY `SERVICES_idx01` (`SUBJECT_ID`,`HADM_ID`),
  ADD KEY `SERVICES_idx02` (`TRANSFERTIME`),
  ADD KEY `SERVICES_idx03` (`CURR_SERVICE`,`PREV_SERVICE`),
  ADD KEY `services_fk_hadm_id` (`HADM_ID`);

ALTER TABLE `social_history`
  ADD KEY `subject_id` (`subject_id`),
  ADD KEY `had_id` (`hadm_id`),
  ADD KEY `note_description` (`note_description`);
ALTER TABLE `social_history` ADD FULLTEXT KEY `text` (`text`);

ALTER TABLE `TRANSFERS`
  ADD PRIMARY KEY (`ROW_ID`),
  ADD KEY `TRANSFERS_idx01` (`SUBJECT_ID`,`HADM_ID`),
  ADD KEY `TRANSFERS_idx02` (`ICUSTAY_ID`),
  ADD KEY `TRANSFERS_idx03` (`CURR_CAREUNIT`,`PREV_CAREUNIT`),
  ADD KEY `TRANSFERS_idx04` (`INTIME`,`OUTTIME`),
  ADD KEY `TRANSFERS_idx05` (`LOS`),
  ADD KEY `transfers_fk_hadm_id` (`HADM_ID`);


ALTER TABLE `medication_adverse_event`
  MODIFY `id` int NOT NULL AUTO_INCREMENT;

ALTER TABLE `microbiology_reports`
  MODIFY `ROW_ID` int NOT NULL AUTO_INCREMENT;

ALTER TABLE `pathways`
  MODIFY `id` int NOT NULL AUTO_INCREMENT;

ALTER TABLE `pathway_treatments`
  MODIFY `id` int NOT NULL AUTO_INCREMENT;

ALTER TABLE `PATIENTS`
  MODIFY `ROW_ID` mediumint UNSIGNED NOT NULL AUTO_INCREMENT;


ALTER TABLE `ADMISSIONS`
  ADD CONSTRAINT `admissions_fk_subject_id` FOREIGN KEY (`SUBJECT_ID`) REFERENCES `PATIENTS` (`SUBJECT_ID`);

ALTER TABLE `CALLOUT`
  ADD CONSTRAINT `callout_fk_hadm_id` FOREIGN KEY (`HADM_ID`) REFERENCES `ADMISSIONS` (`HADM_ID`),
  ADD CONSTRAINT `callout_fk_subject_id` FOREIGN KEY (`SUBJECT_ID`) REFERENCES `PATIENTS` (`SUBJECT_ID`);

ALTER TABLE `CPTEVENTS`
  ADD CONSTRAINT `cptevents_fk_hadm_id` FOREIGN KEY (`HADM_ID`) REFERENCES `ADMISSIONS` (`HADM_ID`),
  ADD CONSTRAINT `cptevents_fk_subject_id` FOREIGN KEY (`SUBJECT_ID`) REFERENCES `PATIENTS` (`SUBJECT_ID`);

ALTER TABLE `DATETIMEEVENTS`
  ADD CONSTRAINT `datetimeevents_fk_cgid` FOREIGN KEY (`CGID`) REFERENCES `CAREGIVERS` (`CGID`),
  ADD CONSTRAINT `datetimeevents_fk_hadm_id` FOREIGN KEY (`HADM_ID`) REFERENCES `ADMISSIONS` (`HADM_ID`),
  ADD CONSTRAINT `datetimeevents_fk_icustay_id` FOREIGN KEY (`ICUSTAY_ID`) REFERENCES `ICUSTAYS` (`ICUSTAY_ID`),
  ADD CONSTRAINT `datetimeevents_fk_itemid` FOREIGN KEY (`ITEMID`) REFERENCES `D_ITEMS` (`ITEMID`),
  ADD CONSTRAINT `datetimeevents_fk_subject_id` FOREIGN KEY (`SUBJECT_ID`) REFERENCES `PATIENTS` (`SUBJECT_ID`);

ALTER TABLE `DIAGNOSES_ICD`
  ADD CONSTRAINT `diagnoses_icd_fk_hadm_id` FOREIGN KEY (`HADM_ID`) REFERENCES `ADMISSIONS` (`HADM_ID`),
  ADD CONSTRAINT `diagnoses_icd_fk_subject_id` FOREIGN KEY (`SUBJECT_ID`) REFERENCES `PATIENTS` (`SUBJECT_ID`);

ALTER TABLE `DRGCODES`
  ADD CONSTRAINT `drgcodes_fk_hadm_id` FOREIGN KEY (`HADM_ID`) REFERENCES `ADMISSIONS` (`HADM_ID`),
  ADD CONSTRAINT `drgcodes_fk_subject_id` FOREIGN KEY (`SUBJECT_ID`) REFERENCES `PATIENTS` (`SUBJECT_ID`);

ALTER TABLE `ICUSTAYS`
  ADD CONSTRAINT `icustays_fk_hadm_id` FOREIGN KEY (`HADM_ID`) REFERENCES `ADMISSIONS` (`HADM_ID`),
  ADD CONSTRAINT `icustays_fk_subject_id` FOREIGN KEY (`SUBJECT_ID`) REFERENCES `PATIENTS` (`SUBJECT_ID`);

ALTER TABLE `INPUTEVENTS_CV`
  ADD CONSTRAINT `inputevents_cv_fk_cgid` FOREIGN KEY (`CGID`) REFERENCES `CAREGIVERS` (`CGID`),
  ADD CONSTRAINT `inputevents_cv_fk_hadm_id` FOREIGN KEY (`HADM_ID`) REFERENCES `ADMISSIONS` (`HADM_ID`),
  ADD CONSTRAINT `inputevents_cv_fk_icustay_id` FOREIGN KEY (`ICUSTAY_ID`) REFERENCES `ICUSTAYS` (`ICUSTAY_ID`),
  ADD CONSTRAINT `inputevents_cv_fk_subject_id` FOREIGN KEY (`SUBJECT_ID`) REFERENCES `PATIENTS` (`SUBJECT_ID`);

ALTER TABLE `INPUTEVENTS_MV`
  ADD CONSTRAINT `inputevents_mv_fk_cgid` FOREIGN KEY (`CGID`) REFERENCES `CAREGIVERS` (`CGID`),
  ADD CONSTRAINT `inputevents_mv_fk_hadm_id` FOREIGN KEY (`HADM_ID`) REFERENCES `ADMISSIONS` (`HADM_ID`),
  ADD CONSTRAINT `inputevents_mv_fk_icustay_id` FOREIGN KEY (`ICUSTAY_ID`) REFERENCES `ICUSTAYS` (`ICUSTAY_ID`),
  ADD CONSTRAINT `inputevents_mv_fk_subject_id` FOREIGN KEY (`SUBJECT_ID`) REFERENCES `PATIENTS` (`SUBJECT_ID`);

ALTER TABLE `LABEVENTS`
  ADD CONSTRAINT `labevents_fk_hadm_id` FOREIGN KEY (`HADM_ID`) REFERENCES `ADMISSIONS` (`HADM_ID`),
  ADD CONSTRAINT `labevents_fk_itemid` FOREIGN KEY (`ITEMID`) REFERENCES `D_LABITEMS` (`ITEMID`),
  ADD CONSTRAINT `labevents_fk_subject_id` FOREIGN KEY (`SUBJECT_ID`) REFERENCES `PATIENTS` (`SUBJECT_ID`);

ALTER TABLE `MICROBIOLOGYEVENTS`
  ADD CONSTRAINT `microbiologyevents_fk_hadm_id` FOREIGN KEY (`HADM_ID`) REFERENCES `ADMISSIONS` (`HADM_ID`),
  ADD CONSTRAINT `microbiologyevents_fk_subject_id` FOREIGN KEY (`SUBJECT_ID`) REFERENCES `PATIENTS` (`SUBJECT_ID`);

ALTER TABLE `noteevents`
  ADD CONSTRAINT `noteevents_fk_cgid` FOREIGN KEY (`CGID`) REFERENCES `CAREGIVERS` (`CGID`),
  ADD CONSTRAINT `noteevents_fk_hadm_id` FOREIGN KEY (`HADM_ID`) REFERENCES `ADMISSIONS` (`HADM_ID`),
  ADD CONSTRAINT `noteevents_fk_subject_id` FOREIGN KEY (`SUBJECT_ID`) REFERENCES `PATIENTS` (`SUBJECT_ID`);

ALTER TABLE `OUTPUTEVENTS`
  ADD CONSTRAINT `outputevents_fk_cgid` FOREIGN KEY (`CGID`) REFERENCES `CAREGIVERS` (`CGID`),
  ADD CONSTRAINT `outputevents_fk_hadm_id` FOREIGN KEY (`HADM_ID`) REFERENCES `ADMISSIONS` (`HADM_ID`),
  ADD CONSTRAINT `outputevents_fk_icustay_id` FOREIGN KEY (`ICUSTAY_ID`) REFERENCES `ICUSTAYS` (`ICUSTAY_ID`),
  ADD CONSTRAINT `outputevents_fk_subject_id` FOREIGN KEY (`SUBJECT_ID`) REFERENCES `PATIENTS` (`SUBJECT_ID`);

ALTER TABLE `PRESCRIPTIONS`
  ADD CONSTRAINT `prescriptions_fk_hadm_id` FOREIGN KEY (`HADM_ID`) REFERENCES `ADMISSIONS` (`HADM_ID`),
  ADD CONSTRAINT `prescriptions_fk_icustay_id` FOREIGN KEY (`ICUSTAY_ID`) REFERENCES `ICUSTAYS` (`ICUSTAY_ID`),
  ADD CONSTRAINT `prescriptions_fk_subject_id` FOREIGN KEY (`SUBJECT_ID`) REFERENCES `PATIENTS` (`SUBJECT_ID`);

ALTER TABLE `PROCEDUREEVENTS_MV`
  ADD CONSTRAINT `procedureevents_mv_fk_cgid` FOREIGN KEY (`CGID`) REFERENCES `CAREGIVERS` (`CGID`),
  ADD CONSTRAINT `procedureevents_mv_fk_hadm_id` FOREIGN KEY (`HADM_ID`) REFERENCES `ADMISSIONS` (`HADM_ID`),
  ADD CONSTRAINT `procedureevents_mv_fk_icustay_id` FOREIGN KEY (`ICUSTAY_ID`) REFERENCES `ICUSTAYS` (`ICUSTAY_ID`),
  ADD CONSTRAINT `procedureevents_mv_fk_subject_id` FOREIGN KEY (`SUBJECT_ID`) REFERENCES `PATIENTS` (`SUBJECT_ID`);

ALTER TABLE `PROCEDURES_ICD`
  ADD CONSTRAINT `procedures_icd_fk_hadm_id` FOREIGN KEY (`HADM_ID`) REFERENCES `ADMISSIONS` (`HADM_ID`),
  ADD CONSTRAINT `procedures_icd_fk_subject_id` FOREIGN KEY (`SUBJECT_ID`) REFERENCES `PATIENTS` (`SUBJECT_ID`);

ALTER TABLE `SERVICES`
  ADD CONSTRAINT `services_fk_hadm_id` FOREIGN KEY (`HADM_ID`) REFERENCES `ADMISSIONS` (`HADM_ID`),
  ADD CONSTRAINT `services_fk_subject_id` FOREIGN KEY (`SUBJECT_ID`) REFERENCES `PATIENTS` (`SUBJECT_ID`);

ALTER TABLE `TRANSFERS`
  ADD CONSTRAINT `transfers_fk_hadm_id` FOREIGN KEY (`HADM_ID`) REFERENCES `ADMISSIONS` (`HADM_ID`),
  ADD CONSTRAINT `transfers_fk_icustay_id` FOREIGN KEY (`ICUSTAY_ID`) REFERENCES `ICUSTAYS` (`ICUSTAY_ID`),
  ADD CONSTRAINT `transfers_fk_subject_id` FOREIGN KEY (`SUBJECT_ID`) REFERENCES `PATIENTS` (`SUBJECT_ID`);
USE `phpmyadmin`;

INSERT INTO `pma__table_uiprefs` (`username`, `db_name`, `table_name`, `prefs`, `last_update`) VALUES
('credentialuser', 'mimiciiiv14', 'ADMISSIONS', '{\"sorted_col\":\"`ADMISSIONS`.`ADMITTIME` DESC\"}', '2021-02-17 21:33:44');

INSERT INTO `pma__table_uiprefs` (`username`, `db_name`, `table_name`, `prefs`, `last_update`) VALUES
('credentialuser', 'mimiciiiv14', 'medication_adverse_event', '{\"sorted_col\":\"`id` ASC\"}', '2021-02-12 14:56:33');

INSERT INTO `pma__table_uiprefs` (`username`, `db_name`, `table_name`, `prefs`, `last_update`) VALUES
('credentialuser', 'mimiciiiv14', 'PATIENTS', '{\"sorted_col\":\"`insurance` ASC\"}', '2021-02-24 21:55:32');

INSERT INTO `pma__relation` (`master_db`, `master_table`, `master_field`, `foreign_db`, `foreign_table`, `foreign_field`) VALUES
('mimiciiiv14', 'NOTEEVENTS', 'CGID', 'mimiciiiv14', 'CAREGIVERS', 'ROW_ID');
SET FOREIGN_KEY_CHECKS=1;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
